name: Ubuntu CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ make
    - name: Build
      run: |
        make clean
        make all
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-build
        path: build/
        retention-days: 5

  test:
    name: Test on Ubuntu
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: ubuntu-build
        path: build
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ make
    - name: Test
      run: make test-all 