name: Ubuntu CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [build, test]
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc g++ make
    - name: Build
      if: matrix.job == 'build'
      run: make clean && make all
    - name: Test
      if: matrix.job == 'test'
      run: make test-all 