name: Windows CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Visual Studio Build Tools
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: Create build directory
      shell: cmd
      run: mkdir build
    - name: Build source files
      shell: cmd
      run: |
        for /d %%w in (src\week*) do (
          mkdir "build\%%~nxw" 2>nul
          for %%p in (%%w\*.cpp) do (
            echo Compiling %%~nxw/%%~nxp...
            cl /std:c++17 /W4 /O2 /EHsc /Fo"build\%%~nxw\" /Fe"build\%%~nxw\%%~np.exe" "%%p"
          )
        )
    - name: Build test framework
      shell: cmd
      run: |
        cl /std:c++17 /W4 /O2 /EHsc /Fo"build\" /Fe"build\test.exe" tests\test.cpp tests\test_runner.cpp
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: build/

  test:
    name: Test on Windows
    needs: build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: windows-build
        path: build
    - name: Run tests
      shell: cmd
      run: |
        for /d %%w in (src\week*) do (
          for %%p in (%%w\*.cpp) do (
            echo.
            echo Testing %%~nxw/%%~np...
            build\test.exe %%~nxw %%~np
          )
        ) 