name: Windows CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Visual Studio Build Tools
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: Build
      shell: cmd
      run: |
        where cl
        where link
        make clean
        make all

  test:
    needs: build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Visual Studio Build Tools
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: Test
      shell: cmd
      run: |
        where cl
        where link
        make test-all 